# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "json"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
delay = 1000  # ms
stop_on_error = true
log = "build-errors.log"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[log]
time = true

[misc]
clean_on_exit = true
